### ISSUE TITLE
You can specify attributes to write to the manifest file here

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/TimerPlugin#3]
https://github.com/HydrologicEngineeringCenter/TimerPlugin/blob/52d34944c0660a8e71f12155fd4dc956b7e032c1/build.gradle#L22-L25

Like this:

https://github.com/HydrologicEngineeringCenter/IRPlugin/blob/c5f62254c46fae79b2c69d58eb7d71af81233bac/build.gradle#L34-L38

**Comment by HenryGeorgist** [comment]
Remember that it is WatPluginMainClass not Rts... and also remember to look at your jar for the folder structure, if there are no subfolders in the jar, do not have any dot delimiters in the path.

**Comment by dvdhoz** [comment]
Thanks, edit made to refer to WatPluginMainClass.
